kitting/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    


kitting/joint_trajectory_controller:
  ros__parameters:
    joints:
      - linear_actuator 
      - kitting_shoulder_pan_joint
      - kitting_shoulder_lift_joint
      - kitting_elbow_joint
      - kitting_wrist_1_joint
      - kitting_wrist_2_joint
      - kitting_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      kitting_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      kitting_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      kitting_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      kitting_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      kitting_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      kitting_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
